//! Element system for Parallax pipelines.
//!
//! This module defines the core traits and types for pipeline elements:
//!
//! - [`Source`]: Produces buffers (e.g., file reader, network receiver)
//! - [`Sink`]: Consumes buffers (e.g., file writer, display)
//! - [`Element`]: Transforms buffers (e.g., filter, encoder)
//! - [`Transform`]: Modern transform trait with multi-output support
//! - [`AsyncSource`], [`AsyncSink`], [`AsyncTransform`]: Async versions
//! - [`Demuxer`]: Routes input to multiple output pads
//!
//! # Design
//!
//! The pipeline uses async-first execution with the [`AsyncElementDyn`] trait:
//! - Elements implement sync or async traits
//! - Adapters convert them to `AsyncElementDyn`
//! - The executor runs everything natively async
//!
//! # Adapters
//!
//! | Source Type | Adapter |
//! |-------------|---------|
//! | `Source` (sync) | [`SourceAdapter`] |
//! | `AsyncSource` | [`AsyncSourceAdapter`] |
//! | `Sink` (sync) | [`SinkAdapter`] |
//! | `AsyncSink` | [`AsyncSinkAdapter`] |
//! | `Transform` (sync) | [`TransformAdapter`] |
//! | `AsyncTransform` | [`AsyncTransformAdapter`] |
//!
//! # Output Types
//!
//! The [`Output`] enum represents the result of processing:
//! - `Output::None`: Buffer was filtered/dropped
//! - `Output::Single`: One output buffer
//! - `Output::Multiple`: Multiple output buffers
//!
//! # Example
//!
//! ```rust,ignore
//! use parallax::element::{Element, Source, Sink, Transform, Output};
//! use parallax::Buffer;
//!
//! // Simple 1-to-1 filter (use Element)
//! struct MyFilter;
//!
//! impl Element for MyFilter {
//!     fn process(&mut self, buffer: Buffer) -> Result<Option<Buffer>> {
//!         Ok(Some(buffer))
//!     }
//! }
//!
//! // Multi-output transform (use Transform directly)
//! struct MySplitter;
//!
//! impl Transform for MySplitter {
//!     fn transform(&mut self, buffer: Buffer) -> Result<Output> {
//!         // Split buffer into multiple outputs
//!         Ok(Output::from(vec![buffer]))
//!     }
//! }
//! ```

mod context;
mod pad;
mod traits;

pub use context::ElementContext;
pub use pad::{Pad, PadDirection, PadTemplate};
pub use traits::{
    // Core async element trait (generated by dynosaur)
    AsyncElementDyn,
    // Async element traits
    AsyncSink,
    // Adapters (all implement AsyncElementDyn)
    AsyncSinkAdapter,
    AsyncSource,
    AsyncSourceAdapter,
    AsyncTransform,
    AsyncTransformAdapter,
    // Sync element traits
    Demuxer,
    DynAsyncElement,
    Element,
    ElementAdapter,
    // Supporting types
    ElementType,
    Output,
    OutputIter,
    PadAddedCallback,
    PadId,
    RoutedOutput,
    Sink,
    SinkAdapter,
    Source,
    SourceAdapter,
    Transform,
    TransformAdapter,
};
