//! Element system for Parallax pipelines.
//!
//! This module defines the core traits and types for pipeline elements:
//!
//! - [`Source`]: Produces buffers (e.g., file reader, network receiver)
//! - [`Sink`]: Consumes buffers (e.g., file writer, display)
//! - [`Element`]: Transforms buffers (e.g., filter, encoder)
//! - [`Transform`]: Modern transform trait with multi-output support
//! - [`AsyncSource`], [`AsyncSink`], [`AsyncTransform`]: Async versions
//! - [`Demuxer`]: Routes input to multiple output pads (1-to-N)
//! - [`Muxer`]: Combines multiple input pads into one output (N-to-1)
//!
//! # Design
//!
//! The pipeline uses async-first execution with the [`AsyncElementDyn`] trait:
//! - Elements implement sync or async traits
//! - Adapters convert them to `AsyncElementDyn`
//! - The executor runs everything natively async
//!
//! # Adapters
//!
//! | Source Type | Adapter |
//! |-------------|---------|
//! | `Source` (sync) | [`SourceAdapter`] |
//! | `AsyncSource` | [`AsyncSourceAdapter`] |
//! | `Sink` (sync) | [`SinkAdapter`] |
//! | `AsyncSink` | [`AsyncSinkAdapter`] |
//! | `Transform` (sync) | [`TransformAdapter`] |
//! | `AsyncTransform` | [`AsyncTransformAdapter`] |
//! | `Demuxer` | [`DemuxerAdapter`] |
//! | `Muxer` | [`MuxerAdapter`] |
//!
//! # Output Types
//!
//! The [`Output`] enum represents the result of processing:
//! - `Output::None`: Buffer was filtered/dropped
//! - `Output::Single`: One output buffer
//! - `Output::Multiple`: Multiple output buffers
//!
//! # Muxer Synchronization
//!
//! For N-to-1 muxers that combine multiple streams, the [`muxer`] module
//! provides synchronization utilities:
//! - [`MuxerSyncState`](muxer::MuxerSyncState): PTS-based synchronization
//! - [`SyncMode`](muxer::SyncMode): Strict, loose, or timed sync
//! - [`StreamType`](muxer::StreamType): Video, audio, subtitle, data
//!
//! # Example
//!
//! ```rust,ignore
//! use parallax::element::{Element, Source, Sink, Transform, Output};
//! use parallax::Buffer;
//!
//! // Simple 1-to-1 filter (use Element)
//! struct MyFilter;
//!
//! impl Element for MyFilter {
//!     fn process(&mut self, buffer: Buffer) -> Result<Option<Buffer>> {
//!         Ok(Some(buffer))
//!     }
//! }
//!
//! // Multi-output transform (use Transform directly)
//! struct MySplitter;
//!
//! impl Transform for MySplitter {
//!     fn transform(&mut self, buffer: Buffer) -> Result<Output> {
//!         // Split buffer into multiple outputs
//!         Ok(Output::from(vec![buffer]))
//!     }
//! }
//! ```

mod context;
pub mod muxer;
mod pad;
mod pipeline_element;
mod traits;

pub use context::{
    ConsumeContext, ElementContext, MemoryView, MemoryViewMut, ProcessContext, ProduceContext,
    ProduceResult,
};
pub use pad::{Pad, PadDirection, PadTemplate};

// New unified element system (Plan 05)
pub use pipeline_element::{
    // Core unified trait
    PipelineElement,
    // Adapter for legacy compatibility
    PipelineElementAdapter,
    // Unified output type
    ProcessOutput,
    ProcessOutputIter,
    // Send variant for async contexts
    SendPipelineElement,
    // Simple element traits (implement these)
    SimpleSink,
    SimpleSource,
    SimpleTransform,
    // Wrapper types (use these to create PipelineElement instances)
    Snk,
    Src,
    Xfm,
};

// Legacy element system (still supported)
pub use traits::{
    // Scheduling affinity
    Affinity,
    // Core async element trait (generated by dynosaur)
    AsyncElementDyn,
    // Async element traits
    AsyncSink,
    // Adapters (all implement AsyncElementDyn)
    AsyncSinkAdapter,
    AsyncSource,
    AsyncSourceAdapter,
    AsyncTransform,
    AsyncTransformAdapter,
    // Adapter for boxed Element trait objects
    BoxedElementAdapter,
    // Sync element traits
    Demuxer,
    DemuxerAdapter,
    DynAsyncElement,
    Element,
    ElementAdapter,
    // Supporting types
    ElementType,
    // Execution hints for automatic scheduling
    ExecutionHints,
    LatencyHint,
    MemoryHint,
    Muxer,
    MuxerAdapter,
    MuxerInput,
    Output,
    OutputIter,
    PadAddedCallback,
    PadId,
    ProcessingHint,
    RoutedOutput,
    Sink,
    SinkAdapter,
    Source,
    SourceAdapter,
    SourceResult,
    Transform,
    TransformAdapter,
    TrustLevel,
};
